# Generated by Django 3.0.6 on 2020-05-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300)),
                ('project_description', models.TextField()),
                ('project_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
